# Copyright © 2026 Beijing Ruishuo Technology Co., Ltd.
# SPDX-License-Identifier: AGPL-3.0-or-later
# Dual-licensed — see LICENSE for details.

packages:
  - 'packages/*'
  - 'app'
allowBuilds:
  '@parcel/watcher': true
  core-js: false
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@typescript-eslint/eslint-plugin@8.67.0'
  - '@typescript-eslint/parser@8.67.0'
  - '@typescript-eslint/project-service@8.67.0'
  - '@typescript-eslint/scope-manager@8.67.0'
  - '@typescript-eslint/tsconfig-utils@8.67.0'
  - '@typescript-eslint/type-utils@8.67.0'
  - '@typescript-eslint/types@8.67.0'
  - '@typescript-eslint/typescript-estree@8.67.0'
  - '@typescript-eslint/utils@8.67.0'
  - '@typescript-eslint/visitor-keys@8.67.0'
  - typescript-eslint@8.67.0
onlyBuiltDependencies: '@parcel/watcher,esbuild,vue-demi'
